name: "dbt_workshop"
version: "1.0.0"
profile: "dbtworkshop"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

models:
  dbt_workshop:
    +materialized: view

    staging:
      +schema: staging
      +tags: ["staging"]
      stripe: {}
      jaffle_shop: {}

    mart:
      +schema: mart
      +tags: ["mart"]
