name: Run Pre-commit Hooks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # чтобы не падало на автогенерации env-ов для 3.10 (твоя ошибка раньше)
      - name: Run pre-commit on all files
        run: |
          pre-commit install
          pre-commit run --all-files
